---
- name: fail if tower_user_password is not set
  fail:
    msg: "tower_user_password is not set"
  when: tower_user_password is undefined or tower_user_password is none or tower_user_password | trim == ''

- name: "create {{ tower_tmp_dir }}"
  file:
    path: "{{ tower_tmp_dir }}"
    state: directory
    mode: 0700
    owner: awx
    group: awx

- name: set full setting string
  set_fact:
    full_setting_string: "\"AWX_PROOT_BASE_PATH\":\"{{ tower_tmp_dir }}\""

- name: get current value of AWX_PROOT_BASE_PATH
  uri:
    url: "{{ tower_rest_url }}"
    user: "{{ tower_user }}"
    password: "{{ tower_user_password }}"
    method: GET 
    validate_certs: false
    return_content: true
  register: jobs_settings

- name: "update tower to use the {{ tower_tmp_dir }} directory"
  uri:
    url: "{{ tower_rest_url }}"
    user: "{{ tower_user }}"
    password: "{{ tower_user_password }}"
    method: PATCH
    body: '{ {{ full_setting_string }} }'
    body_format: json
    validate_certs: false
  when: full_setting_string not in jobs_settings.content
...
